runtime! archlinux.vim

execute pathogen#infect()

" Detect file types
filetype plugin on
" Alternative: use the following to also enable language-dependent indenting.
"filetype plugin indent on
autocmd FileType tex :setlocal spell
autocmd FileType gitcommit :setlocal spell

" Show syntax
syntax on

" Autoindent
set ai

" Tab width
set tabstop=2
set shiftwidth=2
set softtabstop=0

" Expand tab to spaces
set expandtab

" Color column
set cc=81
autocmd FileType gitcommit set cc=73

" Scroll offset in top/bottom
set scrolloff=3

" Instant search
set incsearch

" Highlight search
set hlsearch

" Toggle paste on CTRL+F11
set pastetoggle=<F11>

" Show title
set title

" Theme
"set background=dark
"colorscheme solarized
colorscheme apprentice

" Select after indenting
vnoremap < <gv
vnoremap > >gv

" Remove bad habits with arrows
map <up> <nop>
map <right> <nop>
map <down> <nop>
map <left> <nop>
imap <up> <nop>
imap <right> <nop>
imap <down> <nop>
imap <left> <nop>

" Switch between tabs with (Shift) Tab
map <tab> :tabnext<Enter>
map <S-tab> :tabprevious<Enter>

" Line numbers
function! NumberToggle()
   let [&nu, &rnu] = [!&rnu, &nu+&rnu==1]

   if has("GitGutterDisable")
	   if &nu || &rnu 
		   :GitGutterEnable
		else
		   :GitGutterDisable
		endif
	endif
endfunc

nnoremap <silent> <C-m> :call NumberToggle()<cr>
set relativenumber
set number

" Show the status bar
set laststatus=2

" Remap leader
let mapleader = "-"

"""""""
"" Plugin specifics
""

" NERDTreeTabs
" Leader-n will toggle the tree
map <Leader>n <plug>NERDTreeTabsToggle<CR>

" vim-terraform
let g:terraform_align = 1
let g:terraform_fmt_on_save = 1

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#branch#use_vcscommand = 1


" neocomplete
let g:neocomplete#enable_at_startup = 1


" EasyMotion
"
" Case insensitive
let g:EasyMotion_smartcase = 1

"
" Ctrlp
"
" Ignore
let g:ctrlp_custom_ignore = '\v[\/](\.(git|hg|svn)|bower_components|node_modules|tmp|temp|vendor)$'


" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_ruby_exec = 'rubocop'
let g:syntastic_go_checkers = ['go']


autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
